### ISSUE TITLE
How the conversion is helping in TCO ?

### ISSUE THREAD

**Issue by LOLdevelopr** [krzkaczor/babel-plugin-tailcall-optimization#22]
as far as I know *(which is very limited I guess 😁 )* the previous stack should be deleted but , how the conversion which you mentioned in the docs is helping with the TCO ?
What I understood from the samples is that it is converting the recursion into an iterating while loop ri8 !
It is overcoming the stack error but Is it TCO ?
Please correct me if I am wrong !...
Thanks

**Comment by krzkaczor** [comment]
@LOLdevelopr each function call results in a new stack frame (pushing to callstack). TCO is basically a optimization that uses the fact that old stack frame wont be needed anymore so we might as well just reuse it instead of creating new one.

In JS new function call will always result in a new stack frame so what this plugin tries to achieve is to rewrite those recursive function calls into a loop (without those calls).

This is how we achieve constant number of stack frames on a callstack. I hope that helps 🤞
